from PyQt5.QtWidgets import (
    QLabel,
    QLineEdit,
    # QWidget,
    # QApplication,
    QFormLayout,
    QComboBox,
    # QCheckBox,
    QPushButton,
    # QFileDialog,
    # QPlainTextEdit,
    # QVBoxLayout,
    # QStyle,
    # QMainWindow,
)
from ConSeqUMI.gui.TabWindow import TabWindow


class ConsensusTabWindow(TabWindow):
    def set_instruction_link(self, instructionLinkText) -> None:
        instructionLinkText.appendPlainText(
            "https://github.com/JGEnglishLab/ConSeqUMI/wiki/Consensus-Generation"
        )

    def set_file_layout(self, fileLayout: QFormLayout) -> None:
        self.inputLabel = QLabel("Input Directory Path")
        self.inputLabel.setToolTip(
            "Required. \nPath to directory that only contains fastq files. \nNote that each individual fastq file should contain sequences that contribute to a single consensus. \nIf directing at the 'umi' command output, this will be the 'bins' directory in the 'umi' command output."
        )
        self.inputField = QLineEdit()

        self.inputBrowseButton = QPushButton("Browse")
        self.inputBrowseButton.clicked.connect(lambda: self.get_file(self.inputField))

        fileLayout.addRow(self.inputLabel, self.inputBrowseButton)
        fileLayout.addRow(self.inputField)

        self.outputLabel = QLabel("Output Directory Path")
        self.outputLabel.setToolTip(
            "Required. \nPath where output folder will be saved."
        )
        self.outputField = QLineEdit()
        self.outputBrowseButton = QPushButton("Browse")
        self.outputBrowseButton.clicked.connect(lambda: self.get_file(self.outputField))

        fileLayout.addRow(self.outputLabel, self.outputBrowseButton)
        fileLayout.addRow(self.outputField)

        self.outputNameLabel = QLabel("Output Directory Title (optional)")
        self.outputNameLabel.setToolTip(
            "Optional. \nStart of name of output file generated by the program."
        )
        self.outputNameField = QLineEdit()
        fileLayout.addRow(self.outputNameLabel, self.outputNameField)

    def set_setting_layout(self, settingLayout: QFormLayout) -> None:
        self.consensusAlgorithmLabel = QLabel("Consensus Algorithm")
        self.consensusAlgorithmComboBox = QComboBox()
        self.consensusAlgorithmComboBox.addItems(["pairwise", "lamassemble", "medaka"])
        settingLayout.addRow(
            self.consensusAlgorithmLabel, self.consensusAlgorithmComboBox
        )

        self.minReadsTitle = QLabel("Minimum Reads (optional)")
        self.minReadsTitle.setToolTip(
            "Optional. \nMinimum number of cluster reads required to generate a consensus sequence. \nDefault is 50."
        )
        self.minReadsField = QLineEdit()
        self.minReadsField.setPlaceholderText("50")

        settingLayout.addRow(self.minReadsTitle, self.minReadsField)

        self.processesTitle = QLabel("Process Number (optional)")
        self.processesTitle.setToolTip(
            "Optional. \nNumber of processes to run. \nBy default it will only use 1. \nIf you enter a number beyond the number of processes your computer is capable of, \nthe number of processes will automatically be set to the maximum level for your computer."
        )
        self.processesField = QLineEdit()
        self.processesField.setPlaceholderText("1")
        settingLayout.addRow(self.processesTitle, self.processesField)

    def set_args(self) -> list:
        args = ["cons"]
        if self.inputField.text():
            args.extend(["-i", self.inputField.text()])
        if self.outputField.text():
            output = self.outputField.text()
            if output[-1] != "/":
                output += "/"
            outputName = self.outputNameField.text()
            output += outputName
            args.extend(["-o", output])
        if self.minReadsField.text():
            args.extend(["-m", self.minReadsField.text()])
        if self.processesField.text():
            args.extend(["-p", self.processesField.text()])
        args.extend(["-c", self.consensusAlgorithmComboBox.currentText()])
        return args
